### ISSUE TITLE
Some questions about localization

### ISSUE THREAD

**Issue by cary-rowen** [paulber19/wordAccessEnhancementNVDAAddon#2]
Hello, we are in the process of translating this add-on into Simplified Chinese and are currently over 90% complete.
During this process, we encountered some problems and need to ask you for confirmation.
1. How should "story" be translated, is there a feature or option for this in Word ?for example: Endnotes story.
2. Using alt+windows+f5 in a document with comments to list all comments in the document causes "Row/column headers" to be unchecked in the NVDA document formatting dialog.

Thanks

**Comment by cary-rowen** [comment]
Another bug report:

In the "Design" tab click on "Page Borders...",

Then select the "Page Border" tab in the pop-up dialog,

Then press the tab key once, and select the "None" radio button for the first group of radio buttons,

Tab again to select "Engrave 3D" in the list that follows, then click the "OK" button.

In this case the alt+windows+F1, add-on will be unresponsive and you will always hear the beep sound.

Thanks

**Comment by paulber19** [comment]
i Rowen.
I am very honored by your interest in this add-on and very conscious of 
the hard work involved in translating it.
For your first question, these are WdStoryType enumeration which 
Specifies the story type of a selection or item.
https://docs.microsoft.com/en-us/office/vba/api/word.wdstorytype#main
For the second point, thank you for pointing it out to me.
This is indeed a bug that will be fixed in the next version.
Thanks.
Best regards.

**Comment by paulber19** [comment]
Hi Rowen.
Thanks again for letting me know.
This will also be fixed in the next version.
Best regards.
Paul.

**Comment by cary-rowen** [comment]
thanks Paul,
The information you provided was useful and I was wondering if you have more information to provide for the following items:


- Text modification only in form fields
- Drawing layer object
- Text layer object
- Shape objects
- InLineShape objects

Grateful
